#!/usr/bin/env bash
# This script displays 'Best School' 9 times and 'Hi' 1 time
number=0
while [ $number -lt 10 ]
do
	if [ $number -eq 8 ]; then
		echo "Hi"
		number=$((number+1))
	else
        	echo "Best School"
        	number=$((number+1))
	fi
done
